### ISSUE TITLE
Ajouter l'exemple naviforest

### ISSUE THREAD

**Issue by mborne** [IGNF/validator-api-client#11]
## Contexte

Nouveaux modèles en construction pour https://naviforest.ign.fr (c.f. [github.com - IGNF/validator-config-naviforest](https://github.com/IGNF/validator-config-naviforest#validator-config-naviforest))

## Actions

Ajouter ce(s) modèle(s) au démonstrateur quand ils seront prêt.

**Comment by mborne** [comment]
@cdebarros tu pourras préparer une branche issue_11 et faire une PR quand tu voudras déployer :)

**Comment by cdebarros** [comment]
Je ne peux pas pousser ma branche issue_11, C'est probablement un problème de droits.
Est-ce que quelqu'un peut me donner les droits (@mborne ou @slafayIGN ) ? merci

**Comment by slafayIGN** [comment]
J'ai fait une team @IGNF/validator qui devrait te donner des droits sur tous les dépôts concernés.
