### ISSUE TITLE
Ajouter des liens vers les autres actions possibles depuis le rapport de validation

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/validator-api-client#6]
- [x] téléchargement des fichiers sources
- [x] téléchargement des fichiers normalisés (le plus utile)
- [x] télécharger le rapport au format CSV
- [x] suppression de la validation

**Comment by mborne** [comment]
Hello @slafayIGN ,

J'ai fais quelques retouches d'affichage au passage. Est-ce que ça te convient :

![20221202-validator-api-client](https://user-images.githubusercontent.com/1783064/205343005-3f34d04d-0670-40bf-
85ef-2f21f58b4885.png)

?

**Comment by mborne** [comment]
OK pour Sylvain avec cette première version, on ferme.
